---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install packages
      apt:
        name:
          - nginx
          - nodejs
          - npm
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Create user
      user:
        name: john
        shell: /bin/bash
        password: "{{ 'mypassword' | password_hash('sha512') }}"
        state: present
